language: php

sudo: false

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

before_script:
  - chmod +x scripts/ci-prerun.sh
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --dev

script:
  - scripts/ci-prerun.sh
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpunit

after_success:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml